# Generated by Django 6.0.4 on 2026-04-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Centre-Ville, Zone Nord', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True, help_text="Module 3.1 : Contrôler l'état (Activer/Désactiver)")),
                ('en_panne', models.BooleanField(default=False, help_text='Module 3.3 : Identifier les objets nécessitant maintenance')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Module 3.1 : Test de connectivité')),
                ('places_occupees', models.IntegerField(default=0)),
                ('places_totales', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.point')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('ACCIDENT', 'Accident'), ('INONDATION', 'Inondation'), ('PANNE_ECLAIRAGE', 'Panne de lampadaire'), ('TRAVAUX', 'Travaux')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('gravite', models.IntegerField(default=1, help_text='De 1 à 5')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.point')),
            ],
        ),
        migrations.CreateModel(
            name='Feu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True, help_text="Module 3.1 : Contrôler l'état (Activer/Désactiver)")),
                ('en_panne', models.BooleanField(default=False, help_text='Module 3.3 : Identifier les objets nécessitant maintenance')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Module 3.1 : Test de connectivité')),
                ('etat_actuel', models.CharField(choices=[('VERT', 'Vert'), ('ORANGE', 'Orange'), ('ROUGE', 'Rouge')], default='ROUGE', max_length=10)),
                ('temps_avant_changement', models.IntegerField(default=30)),
                ('cycle_config', models.JSONField(default=dict, help_text="Ex: {'vert': 30, 'orange': 5, 'rouge': 30}")),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.point')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_vehicules_actuel', models.IntegerField(default=0)),
                ('feux', models.ManyToManyField(blank=True, related_name='routes', to='map.feu')),
                ('points', models.ManyToManyField(related_name='routes', to='map.point')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True, help_text="Module 3.1 : Contrôler l'état (Activer/Désactiver)")),
                ('en_panne', models.BooleanField(default=False, help_text='Module 3.3 : Identifier les objets nécessitant maintenance')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Module 3.1 : Test de connectivité')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('vitesse', models.FloatField(default=0.0)),
                ('historique_points', models.ManyToManyField(blank=True, related_name='historique_vehicules', to='map.point')),
                ('point_actuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules_ici', to='map.point')),
                ('prochain_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules_vers', to='map.point')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='point',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='map.zone'),
        ),
    ]
