# Generated by Django 6.0.4 on 2026-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feu',
            name='connectivite',
            field=models.CharField(default='Wi-Fi', help_text='Type de réseau (Wi-Fi, 4G, LoRa...)', max_length=50),
        ),
        migrations.AddField(
            model_name='feu',
            name='description',
            field=models.TextField(blank=True, help_text='Description contenant potentiellement des mots-clés'),
        ),
        migrations.AddField(
            model_name='feu',
            name='est_connecte',
            field=models.BooleanField(default=True, help_text='État de la connexion au réseau'),
        ),
        migrations.AddField(
            model_name='feu',
            name='marque',
            field=models.CharField(blank=True, default='Non spécifiée', help_text='Ex: Phillips, Siemens...', max_length=50),
        ),
        migrations.AddField(
            model_name='feu',
            name='mots_cles',
            field=models.CharField(blank=True, help_text='Pour le moteur de recherche', max_length=255),
        ),
        migrations.AddField(
            model_name='feu',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, help_text='Niveau de batterie en %', null=True),
        ),
        migrations.AddField(
            model_name='feu',
            name='type_objet',
            field=models.CharField(default='Non défini', help_text='Ex: Feu, Caméra, Thermostat, Capteur', max_length=50),
        ),
        migrations.AddField(
            model_name='parking',
            name='connectivite',
            field=models.CharField(default='Wi-Fi', help_text='Type de réseau (Wi-Fi, 4G, LoRa...)', max_length=50),
        ),
        migrations.AddField(
            model_name='parking',
            name='description',
            field=models.TextField(blank=True, help_text='Description contenant potentiellement des mots-clés'),
        ),
        migrations.AddField(
            model_name='parking',
            name='est_connecte',
            field=models.BooleanField(default=True, help_text='État de la connexion au réseau'),
        ),
        migrations.AddField(
            model_name='parking',
            name='marque',
            field=models.CharField(blank=True, default='Non spécifiée', help_text='Ex: Phillips, Siemens...', max_length=50),
        ),
        migrations.AddField(
            model_name='parking',
            name='mots_cles',
            field=models.CharField(blank=True, help_text='Pour le moteur de recherche', max_length=255),
        ),
        migrations.AddField(
            model_name='parking',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, help_text='Niveau de batterie en %', null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='type_objet',
            field=models.CharField(default='Non défini', help_text='Ex: Feu, Caméra, Thermostat, Capteur', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='connectivite',
            field=models.CharField(default='Wi-Fi', help_text='Type de réseau (Wi-Fi, 4G, LoRa...)', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='description',
            field=models.TextField(blank=True, help_text='Description contenant potentiellement des mots-clés'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='est_connecte',
            field=models.BooleanField(default=True, help_text='État de la connexion au réseau'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(blank=True, default='Non spécifiée', help_text='Ex: Phillips, Siemens...', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='mots_cles',
            field=models.CharField(blank=True, help_text='Pour le moteur de recherche', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, help_text='Niveau de batterie en %', null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_objet',
            field=models.CharField(default='Non défini', help_text='Ex: Feu, Caméra, Thermostat, Capteur', max_length=50),
        ),
        migrations.AlterField(
            model_name='feu',
            name='cycle_config',
            field=models.JSONField(default=dict, help_text="Paramètres d'utilisation : {'vert': 30, 'orange': 5, 'rouge': 30}"),
        ),
        migrations.AlterField(
            model_name='feu',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feu',
            name='en_panne',
            field=models.BooleanField(default=False, help_text='Identifier les objets nécessitant maintenance'),
        ),
        migrations.AlterField(
            model_name='feu',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Activer/Désactiver'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='en_panne',
            field=models.BooleanField(default=False, help_text='Identifier les objets nécessitant maintenance'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Activer/Désactiver'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='en_panne',
            field=models.BooleanField(default=False, help_text='Identifier les objets nécessitant maintenance'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Activer/Désactiver'),
        ),
    ]
