# Generated by Django 6.0.4 on 2026-04-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_feu_connectivite_feu_description_feu_est_connecte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='fin',
        ),
        migrations.AddField(
            model_name='feu',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='map.zone'),
        ),
        migrations.AddField(
            model_name='parking',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='map.zone'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='map.zone'),
        ),
        migrations.AlterField(
            model_name='feu',
            name='connectivite',
            field=models.CharField(default='Wi-Fi', max_length=50),
        ),
        migrations.AlterField(
            model_name='feu',
            name='cycle_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='feu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feu',
            name='en_panne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feu',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feu',
            name='est_connecte',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feu',
            name='marque',
            field=models.CharField(blank=True, default='Non spécifiée', max_length=50),
        ),
        migrations.AlterField(
            model_name='feu',
            name='mots_cles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feu',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feu',
            name='type_objet',
            field=models.CharField(default='Non défini', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='gravite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('INONDATION', 'Inondation'), ('PANNE_ECLAIRAGE', 'Panne'), ('TRAVAUX', 'Travaux')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parking',
            name='connectivite',
            field=models.CharField(default='Wi-Fi', max_length=50),
        ),
        migrations.AlterField(
            model_name='parking',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='en_panne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parking',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='est_connecte',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='marque',
            field=models.CharField(blank=True, default='Non spécifiée', max_length=50),
        ),
        migrations.AlterField(
            model_name='parking',
            name='mots_cles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parking',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type_objet',
            field=models.CharField(default='Non défini', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='connectivite',
            field=models.CharField(default='Wi-Fi', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='en_panne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='est_connecte',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(blank=True, default='Non spécifiée', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='mots_cles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_objet',
            field=models.CharField(default='Non défini', max_length=50),
        ),
    ]
