# Generated by Django 6.0.4 on 2026-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_incident_fin_feu_zone_parking_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('TRAFFIC', 'Gestion du Trafic'), ('SAFETY', 'Sécurité & Incidents'), ('ENERGY', 'Optimisation Énergie'), ('MAINTENANCE', 'Maintenance Automatique')], default='TRAFFIC', max_length=20)),
                ('declencheur_champ', models.CharField(max_length=50)),
                ('operateur', models.CharField(choices=[('>', '>'), ('<', '<'), ('==', '=='), ('in', 'Contient')], max_length=5)),
                ('valeur_seuil', models.CharField(max_length=100)),
                ('action_champ', models.CharField(max_length=50)),
                ('action_valeur', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feu',
            name='connectivite',
        ),
        migrations.RemoveField(
            model_name='feu',
            name='est_connecte',
        ),
        migrations.RemoveField(
            model_name='feu',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='feu',
            name='mots_cles',
        ),
        migrations.RemoveField(
            model_name='feu',
            name='type_objet',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='connectivite',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='est_connecte',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='mots_cles',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='type_objet',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='connectivite',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='est_connecte',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='mots_cles',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='type_objet',
        ),
        migrations.AddField(
            model_name='feu',
            name='consommation_actuelle',
            field=models.FloatField(default=0.0, help_text='Watts/h'),
        ),
        migrations.AddField(
            model_name='feu',
            name='horaires_fonctionnement',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feu',
            name='parametres_service',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feu',
            name='temperature_actuelle',
            field=models.FloatField(blank=True, help_text='En °C', null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='consommation_actuelle',
            field=models.FloatField(default=0.0, help_text='Watts/h'),
        ),
        migrations.AddField(
            model_name='parking',
            name='horaires_fonctionnement',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parking',
            name='parametres_service',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parking',
            name='temperature_actuelle',
            field=models.FloatField(blank=True, help_text='En °C', null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='consommation_actuelle',
            field=models.FloatField(default=0.0, help_text='Watts/h'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='horaires_fonctionnement',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='parametres_service',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='temperature_actuelle',
            field=models.FloatField(blank=True, help_text='En °C', null=True),
        ),
        migrations.AlterField(
            model_name='feu',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, help_text='En %', null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, help_text='En %', null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, help_text='En %', null=True),
        ),
    ]
