# Generated by Django 6.0.4 on 2026-04-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_scenario_remove_feu_connectivite_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
