# Generated by Django 6.0.4 on 2026-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_delete_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='feu',
            name='type_objet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parking',
            name='type_objet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_objet',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
