# Generated by Django 6.0.4 on 2026-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_feu_type_objet_parking_type_objet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('TRAFFIC', 'Gestion du Trafic'), ('SAFETY', 'Sécurité & Incidents'), ('ENERGY', 'Optimisation Énergie'), ('MAINTENANCE', 'Maintenance Automatique')], default='TRAFFIC', max_length=20)),
                ('declencheur_champ', models.CharField(max_length=50)),
                ('operateur', models.CharField(choices=[('>', '>'), ('<', '<'), ('==', '=='), ('in', 'Contient')], max_length=5)),
                ('valeur_seuil', models.CharField(max_length=100)),
                ('action_champ', models.CharField(max_length=50)),
                ('action_valeur', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
    ]
