# Generated by Django 6.0.4 on 2026-04-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_id', models.IntegerField()),
                ('type_objet', models.CharField(choices=[('vehicule', 'Véhicule'), ('feu', 'Feu'), ('parking', 'Parking')], max_length=20)),
                ('date_mesure', models.DateTimeField(auto_now_add=True)),
                ('consommation_kwh', models.FloatField(default=0.0)),
                ('est_en_panne', models.BooleanField(default=False)),
                ('valeur_specifique', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_mesure'],
                'indexes': [models.Index(fields=['type_objet', 'objet_id'], name='map_histori_type_ob_aab4c1_idx'), models.Index(fields=['date_mesure'], name='map_histori_date_me_ac79dd_idx')],
            },
        ),
    ]
