# Generated by Django 6.0.4 on 2026-04-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_historiqueobjet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_evenement', models.CharField(choices=[('festival', 'Festival'), ('marche', 'Marché'), ('concert', 'Concert'), ('autre', 'Autre Événement')], max_length=30)),
                ('date_debut', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.point')),
            ],
        ),
        migrations.CreateModel(
            name='LieuInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('musee', 'Musée'), ('parc', 'Parc'), ('restaurant', 'Restaurant'), ('bibliotheque', 'Bibliothèque')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.point')),
            ],
        ),
    ]
