# Generated by Django 6.0.4 on 2026-04-25 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_evenement_lieuinteret'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='consommation_actuelle',
            field=models.FloatField(default=0.0, help_text='Watts/h'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='en_panne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='horaires_fonctionnement',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evenement',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, help_text='En %', null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='parametres_service',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evenement',
            name='temperature_actuelle',
            field=models.FloatField(blank=True, help_text='En °C', null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='type_objet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='map.zone'),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='consommation_actuelle',
            field=models.FloatField(default=0.0, help_text='Watts/h'),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='en_panne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='horaires_fonctionnement',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='niveau_batterie',
            field=models.IntegerField(blank=True, help_text='En %', null=True),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='parametres_service',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='temperature_actuelle',
            field=models.FloatField(blank=True, help_text='En °C', null=True),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='type_objet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='map.zone'),
        ),
    ]
