# Generated by Django 6.0.4 on 2026-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_evenement_consommation_actuelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lieuinteret',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lieuinteret',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
