# Generated by Django 6.0.4 on 2026-04-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_evenement_description_alter_evenement_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='zone',
        ),
    ]
