# Generated by Django 6.0.4 on 2026-04-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_remove_point_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueobjet',
            name='frequentation',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueobjet',
            name='objet_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historiqueobjet',
            name='type_objet',
            field=models.CharField(choices=[('vehicule', 'Véhicule'), ('feu', 'Feu'), ('parking', 'Parking'), ('lieu', "Lieu d'intérêt"), ('evenement', 'Événement')], max_length=20),
        ),
    ]
