# Generated by Django 6.0.4 on 2026-04-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_historiqueobjet_frequentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(choices=[('vehicule', 'Véhicule'), ('feu', 'Feu'), ('parking', 'Parking'), ('lieu', "Lieu d'intérêt"), ('evenement', 'Événement')], max_length=20)),
                ('objet_id', models.PositiveIntegerField()),
                ('code', models.CharField(default='SURCONSOMMATION', max_length=50)),
                ('niveau', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('valeur_mesuree', models.FloatField(default=0.0)),
                ('valeur_reference', models.FloatField(default=0.0)),
                ('ecart_percent', models.FloatField(default=0.0)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('declenchee_le', models.DateTimeField(auto_now_add=True)),
                ('acquittee_le', models.DateTimeField(blank=True, null=True)),
                ('resolue_le', models.DateTimeField(blank=True, null=True)),
                ('contexte', models.JSONField(blank=True, default=dict)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.zone')),
            ],
            options={
                'ordering': ['-declenchee_le'],
                'indexes': [models.Index(fields=['type_objet', 'objet_id', 'statut'], name='map_alerteo_type_ob_0c0c7d_idx'), models.Index(fields=['zone', 'declenchee_le'], name='map_alerteo_zone_id_485a27_idx'), models.Index(fields=['code', 'declenchee_le'], name='map_alerteo_code_7ee2f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegleAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('type_objet', models.CharField(choices=[('vehicule', 'Véhicule'), ('feu', 'Feu'), ('parking', 'Parking'), ('lieu', "Lieu d'intérêt"), ('evenement', 'Événement')], max_length=20)),
                ('seuil_surconsommation', models.FloatField(default=1.35, help_text='Ratio applique a la moyenne historique avant de lever une alerte.')),
                ('seuil_absolu_kwh', models.FloatField(default=0.5, help_text='Ecart minimal en kWh pour eviter les faux positifs.')),
                ('fenetre_analyse_heures', models.PositiveIntegerField(default=24)),
                ('echantillons_minimum', models.PositiveIntegerField(default=6)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30)),
                ('est_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.zone')),
            ],
            options={
                'ordering': ['type_objet', 'zone_id', 'nom'],
                'indexes': [models.Index(fields=['type_objet', 'zone'], name='map_regleal_type_ob_d8d599_idx'), models.Index(fields=['est_active'], name='map_regleal_est_act_1b3b65_idx')],
            },
        ),
    ]
