# Generated by Django 6.0.4 on 2026-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_alerteobjet_reglealerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='frequentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lieuinteret',
            name='frequentation',
            field=models.IntegerField(default=0),
        ),
    ]
