# Generated by Django 6.0.4 on 2026-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='points_gagnes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre'), ('NR', 'Non renseigné')], default='NR', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='niveau',
            field=models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], default='DEBUTANT', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.FloatField(default=0.0, help_text="Système de points pour l'évolution du niveau"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_membre',
            field=models.CharField(default='Citoyen', help_text='Ex: Citoyen, Agent municipal, Touriste...', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('VISITEUR', 'Visiteur'), ('SIMPLE', 'Simple'), ('COMPLEXE', 'Complexe'), ('ADMIN', 'Administrateur')], default='SIMPLE', max_length=20),
        ),
    ]
